environment:
  matrix:
    - nodejs_version: "9"
    - nodejs_version: "8"
    - nodejs_version: "6"
    - nodejs_version: "4"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - gulp && jest && yarn lint

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"

build: off
deploy: off

environment:
  YARN_IGNORE_ENGINES: true
